# -*- mode: ruby -*-

Vagrant.configure('2') do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = 'polar'
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 4096
  end

  config.vm.network :forwarded_port, guest: 80, host: 8080

  # bring the system up to date
  config.vm.provision 'shell', inline: <<-SHELL
    sudo apt-get -y autoremove
    sudo apt-get -y update
    sudo apt-get -y upgrade
  SHELL
end
